var PROJECTS = [
  {
    id:1, name:"Balakhivka Graphite Deposit",
    status:"halted", type:"Extraction", country:"Ukraine",
    lat:48.4759556, lng:33.2124389,
    mat:"Graphite", neon:"#00e5ff", fill:"#007a99",
    conflict:true,
    promoter:"Pobuzhzhya's Development LLC",
    linked:"BGV Group Management",
    notes:"The investment group's companies operate in 13 deposits across 5 regions of Ukraine.",
    desc:"Open-pit graphite mine and processing plant under development in Kirovohrad Oblast, Ukraine, targeting battery-grade spherical graphite for lithium-ion batteries. Operated by BGV Group subsidiary. $450M investment required. Production start planned for 2028, severely delayed by Russian invasion.",
    applications:"Lithium-ion batteries, EVs",
    eia:"Not completed — suspended due to active conflict.",
    lic:"Granted — obtained 19 June 2019 for a period of 20 years. All activities suspended due to active armed conflict.",
    prod:"50,000 t/yr graphite concentrate; 19,000 t/yr spherical graphite",
    conflictDetail:"Active armed conflict (Russian invasion) has halted all project activities. BGV Group sister company Perzhanska Ore Company allegedly obtained permission to extract beryllium inside a natural reserve — investigation ongoing.",
    conflictLink:"https://www.business-humanrights.org/en/latest-news/ukraine-perzhanska-ore-company-allegedly-illegally-received-permission-to-extract-beryllium-in-natural-reserve-investigation-ongoing-incl-co-comments/",
    web:"https://www.bgv-graphite.com.ua/en/about-the-project/"
  },
  {
    id:2, name:"CaledoNi Project",
    status:"active", type:"Processing", country:"New Caledonia",
    lat:-22.254025, lng:166.4438056,
    mat:"Nickel", neon:"#76ff03", fill:"#3d8a00",
    conflict:false,
    promoter:"Societe Le Nickel (SLN)",
    linked:"Eramet (56% owner of SLN); French State (26%)",
    notes:"SLN is the world's oldest nickel mining company tied to the colonisation of New Caledonia and its Kanak people, founded in 1880, subsidiary of Eramet. Faced severe civil unrest in 2024.",
    desc:"Project in deep financial difficulty with the French state providing emergency support. Industrial upgrade at SLN's Doniambo ferronickel smelter in Noumea adding a third line to the existing Dust Extrusion Workshop (AEP).",
    applications:"Stainless steel; battery-grade nickel sulphate for EV batteries",
    eia:"Not required under ICPE framework — upgrade of existing permitted facility. Smelter emits significant ore particulates and SO2.",
    lic:"Partial — base operating licence in place under Province Sud ICPE framework. Amended ICPE permit for the third AEP line not yet confirmed. Completion targeted by 2028.",
    prod:"32,900 t ferronickel produced in 2024; nameplate capacity ~54,000 t/yr",
    conflictDetail:"Community conflict status unknown. SLN is historically tied to the colonisation of New Caledonia and the Kanak people (founded 1880). Civil unrest severely disrupted operations in 2024, after the French Parliament adopted a bill changing the territory’s voting rules",
    conflictLink:"",
    web:"https://sln.eramet.com/sln/nos-engagements/le-projet-caledoni-de-la-sln/"
  },
  {
    id:3, name:"Greenland Graphite / Norgraph",
    status:"active", type:"Integrated: Extraction and Processing", country:"Greenland and Norway",
    lat:60.3169028, lng:-44.9250972,
    mat:"Graphite", neon:"#00e5ff", fill:"#007a99",
    conflict:true,
    promoter:"GreenRoc Strategic Materials Plc",
    linked:"GreenRoc Strategic Materials Plc (AIM: GROC); Norgraph a/s (Norwegian processing subsidiary)",
    notes:"EBRD and EU ERMA backing sought.",
    desc:"Integrated graphite project: extraction from the Amitsoq deposit in the Nanortalik region — one of the world's highest-grade graphite deposits — processing into active anode material (AAM) at Heroya Industrial Park in Norway. Historic mine last operational in 1922.",
    applications:"Lithium-ion battery anodes (active anode material for EVs); advanced industrial uses",
    eia:"Pending — public consultation required before construction. Graphite dust risk to glacial and marine environments. Processing in Norway under EU environmental standards.",
    lic:"Granted — 30-year exploitation licence signed 8 December 2025 by the Government of Greenland. Mining must commence by 31 December 2030. Impact Benefit Agreement and Mine and Closure Plan still required.",
    prod:"~80,000 t/yr graphite concentrate (400,000 t/yr ore processed); 22-year mine life",
    conflictDetail:"Significant indigenous and decolonisation concerns. Greenlandic independence advocates and Inuit community members have publicly opposed mining.",
    conflictLink:"https://fordhampoliticalreview.org/we-will-stop-the-mine-mining-decolonization-and-greenlandic-independence/",
    web:"https://greenrocplc.com/"
  },
  {
    id:4, name:"Integrated Dumont Nickel Project",
    status:"active", type:"Extraction", country:"Canada",
    lat:48.5666278, lng:-78.1594694,
    mat:"Nickel, Cobalt", neon:"#76ff03", fill:"#3d8a00",
    conflict:true,
    promoter:"Magneto Investments Limited Partnership",
    linked:"Nion Nickel Inc. (owner); Kinterra Capital (manager); Waterton Global Resource Management (prior advisor); NiVolt Technologies (downstream processing partner)",
    notes:"Owned by Nion Nickel Inc., managed by Kinterra Capital, a Toronto-based private equity firm. Previously known as RNC Minerals. Project changed hands multiple times.",
    desc:"Open-pit mine producing nickel sulphide concentrate for 30+ years in the Abitibi region of Quebec, Canada.",
    applications:"Battery-grade nickel for EV cathodes; cobalt by-product for batteries",
    eia:"Completed (2015) — very large waste rock and tailings storage area; long-term watershed pollution risk; disturbance of boreal forest ecosystems in the Abitibi region. Project located on ancestral territory of the Abitibiwinni First Nation near Lake Chicobi.",
    lic:"Granted — fully permitted and construction-ready. Indigenous Impact and Benefit Agreement in place with Abitibiwinni First Nation. Construction decision anticipated 2025-2026.",
    prod:"Average 39,000 t/yr nickel in sulphide concentrate over 30-year mine life, ramping to 50,000 t/yr in Phase II; ~1,100 t/yr cobalt",
    conflictDetail:"Project will affect water and land of the Abitibiwinni First Nation near Lake Chicobi, although an Indigenous Impact and Benefit Agreement (IBA) has been reached. Concerns were raised about inadequate consultation during earlier permitting stages.",
    conflictLink:"https://iaac-aeic.gc.ca/050/evaluations/document/120673?culture=en-CA",
    web:"https://www.kinterracapital.com/portfolio/nion-nickel-inc"
  },
  {
    id:5, name:"Jadar",
    status:"cancelled", type:"Extraction", country:"Serbia",
    lat:44.5330556, lng:19.3,
    mat:"Lithium, Boron", neon:"#d500f9", fill:"#8800b3",
    conflict:true,
    promoter:"Rio Tinto (Local entity: Rio Sava Exploration doo)",
    linked:"Rio Tinto plc (LSE/ASX/NYSE: RIO); local entity Rio Sava Exploration doo",
    notes:"Rio Tinto is one of the world's largest mining companies, operating in 35 countries. It has been involved in environmental scandals displacing native peoples in Mongolia, Madagascar, Papua New Guinea, Brazil. Discovered jadarite in 2000s. Suspended project in November 2025.",
    desc:"Underground jadarite mine near Loznica, Serbia. Contains the world's only known deposit of jadarite — a new mineral unique to this site containing lithium and boron.",
    applications:"Battery-grade lithium carbonate for EV batteries; boron for metallurgy and glass",
    eia:"Not approved — Serbia's Ministry of Environmental Protection issued EIA scope requirements in November 2024. Rio Tinto given 12 months to submit full EIA documentation. EIA not yet approved.",
    lic:"Cancelled — licences cancelled January 2022 after mass protests. Constitutional Court ruled cancellation unlawful. Spatial plan reinstated July 2024. Rio Tinto suspended the project in November 2025 and placed it into care and maintenance.",
    prod:"58,000 t/yr lithium carbonate equivalent (LCE) at full production; 40-year mine life",
    conflictDetail:"Massive community opposition in Serbia. Thousands protested against the mine citing water and land contamination fears. Licences cancelled January 2022 following mass protests. Rio Tinto has a documented history of environmental scandals displacing communities in multiple countries.",
    conflictLink:"https://www.business-humanrights.org/en/from-us/briefings/tmt-2021/you-cant-eat-lithium-community-consent-and-access-to-information-in-transition-mineral-mining-exploration-in-europe-and-north-america/",
    web:"https://www.riotinto.com/en/operations/europe-me/jadar"
  },
  {
    id:6, name:"Kobaloni Energy Zambia Ltd",
    status:"active", type:"Processing", country:"Zambia",
    lat:-15.4961583, lng:28.3846278,
    mat:"Cobalt", neon:"#2979ff", fill:"#1a56cc",
    conflict:true,
    promoter:"Kobaloni Energy Zambia Limited",
    linked:"Vision Blue Resources; Africa Finance Corporation (AFC)",
    notes:"Kobaloni Energy is developing the first large-scale, battery-grade cobalt sulphate refinery on the African continent.",
    desc:"Cobalt hydrometallurgical refinery in Zambia's Copperbelt processing cobalt hydroxide feedstock from DRC into battery-grade cobalt sulphate crystals for the automotive battery industry.",
    applications:"Lithium-ion battery cathodes (NMC); EV batteries; consumer electronics",
    eia:"Pending — no public EIA completed. Environmental permit application submitted to Zambia Environmental Management Agency (ZEMA). Tailings storage facilities will be required.",
    lic:"Pending — environmental and operational licences under application with ZEMA. No final licences granted yet.",
    prod:"6,000 tpa of cobalt sulphate",
    conflictDetail:"There is in unkown community confilcts with this particular project; Project area includes villages and likely displacement; There are broader concerns about DRC cobalt supply chain including child labour and artisanal mining conditions.",
    conflictLink:"https://papers.ssrn.com/sol3/papers.cfm?abstract_id=4802367",
    web:"https://www.kobaloni.com/"
  },
  {
    id:7, name:"Maniry Graphite Mine Project",
    status:"active", type:"Extraction", country:"Madagascar",
    lat:-24.5048472, lng:44.8905694,
    mat:"Graphite", neon:"#00e5ff", fill:"#007a99",
    conflict:true,
    promoter:"Evion Group NL",
    linked:"Evion Group NL (ASX: EVG); Panthera Graphite Technologies (India JV with Metachem); Urbix Inc. (US, non-binding offtake)",
    notes:"Evion Group is a vertically integrated graphite developer with projects in Madagascar, India and Europe. Small ASX-listed company. Previously known as BlackEarth Minerals.",
    desc:"Open-pit flake graphite mine in southwest Madagascar targeting battery-grade product.",
    applications:"Lithium-ion battery anodes; expandable graphite for industrial uses; battery anode material (BAM) for EU market",
    eia:"Pending — ESIA completed by Resolve Consulting and submitted to Madagascar's Office National pour l'Environnement (ONE) for review. Open-cast mining near endemic biodiversity zones. Graphite dust risk to local agriculture and waterways.",
    lic:"Pending — Madagascar's new mining code (adopted late 2023) facilitates granting of development and production licences. BCMM approved licence conversion process. Environmental permit still pending ONE approval.",
    prod:"During the first three years an average of 35-45 ktpa; 50-60 ktpa of graphite after year 4",
    conflictDetail:"Villagers near the proposed mine site have reported inadequate consultation, fear of land dispossession, and disruption to subsistence farming. No formal FPIC process documented publicly.",
    conflictLink:"https://news.mongabay.com/2023/04/madagascar-what-happens-to-villagers-when-a-graphite-mine-comes-knocking/",
    web:"https://eviongroup.com/maniry-project/"
  },
  {
    id:8, name:"Nussir",
    status:"active", type:"Extraction", country:"Norway",
    lat:70.4536333, lng:24.2803444,
    mat:"Copper", neon:"#ff6d00", fill:"#b34d00",
    conflict:true,
    promoter:"Nussir ASA",
    linked:"Blue Moon Metals Inc. (acquired Nussir ASA 100% in February 2025); Hartree Partners and Oaktree Capital (financiers)",
    notes:"Nussir ASA was previously owned by a private Norwegian company. Blue Moon Metals acquired full ownership in February 2025 and is now advancing to construction. Heavily contested by Sami people — led to withdrawal of Aurubis AG in 2021 due to sustainability concerns.",
    desc:"Underground copper mine near Repparfjord in Finnmark; Norway's largest copper deposit with foreseen sea-tailings for mineral waste. The project will affect Sami communities as well as local people that live off fishing activities.",
    applications:"Copper for electrical wiring, EV motors, renewable energy infrastructure, electronics",
    eia:"Completed — emission permit granted by Ministry of Climate and Environment, 19 December 2016, including permission for submarine tailings disposal (STD) into Repparfjord. Up to 2 million tonnes of sea-tailing waste per year.",
    lic:"Granted — all primary permits in place: operating licence, extraction permit, environmental permit, zoning plan. All third-party appeals exhausted. Mining must commence by end of 2027.",
    prod:"19,000 tonnes per annum of copper and up to 2 million tonnes of sea-tailing waste",
    conflictDetail:"Heavily and persistently contested by Sami reindeer herding communities. The planned submarine tailings disposal (STD) into Repparfjord threatens the fjord ecosystem and traditional fishing rights. Aurubis AG withdrew as offtake partner in 2021 citing sustainability concerns.",
    conflictLink:"https://www.voices-ngo.ch/en/publications/case-studies/planned-copper-mines-threaten-the-sami-culture/",
    web:"https://nussir.no/prosjektet/"
  },
  {
    id:9, name:"Sao Miguel Paulista (SMP) Refinery Restart",
    status:"active", type:"Processing", country:"Brazil",
    lat:-23.4831556, lng:-46.4343111,
    mat:"Nickel, Cobalt", neon:"#76ff03", fill:"#3d8a00",
    conflict:false,
    promoter:"Jervois Brasil Metalurgia Ltda.",
    linked:"Jervois Global Limited (parent); Traxys Europe (MHP feedstock supplier, 25% of feed requirement); AustralianSuper (largest shareholder)",
    notes:"Jervois is an Australian-listed integrated cobalt and nickel company. It previously suspended the SMP restart in June 2023 due to low cobalt prices and funding gaps, then took a new positive FID in late 2025.",
    desc:"Electrolytic nickel and cobalt refinery in Sao Paulo, Brazil. Originally built in the 1970s-80s, operated for over 30 years before being placed on care and maintenance in 2016. Jervois acquired it in 2022 and is restarting it. It will be Latin America's only Class 1 electrolytic nickel and cobalt refinery. Construction commenced January 2026; commercial production expected 2027.",
    applications:"Battery-grade Class 1 nickel and cobalt metal cathode for EV batteries and consumer electronics; nickel also used in stainless steel and aerospace alloys",
    eia:"Completed — Environmental Installation License (LPI) granted by CETESB (Sao Paulo State environmental regulator) in September 2022. Operating licence from Sao Paulo City Hall also renewed.",
    lic:"Granted — Environmental Installation License issued by CETESB in September 2022. Operating permit from Sao Paulo City Hall renewed. Construction began January 2026; commercial production targeted for 2027.",
    prod:"12,000 t/yr refined nickel metal cathode and 2,000 t/yr cobalt metal cathode; historic nameplate of 25,000 t/yr nickel is a longer-term target",
    conflictDetail:"Community conflict status unknown. The refinery is located in an established urban industrial neighbourhood of Sao Paulo city with existing infrastructure. Previously operated for over 30 years without significant recorded conflict.",
    conflictLink:"",
    web:"https://jervoisglobal.com/projects/sao-miguel-paulista-refinery/"
  },
  {
    id:10, name:"Sarytogan Graphite Project",
    status:"active", type:"Extraction", country:"Kazakhstan",
    lat:48.652325, lng:73.9329889,
    mat:"Graphite", neon:"#00e5ff", fill:"#007a99",
    conflict:false,
    promoter:"Sarytogan Graphite Limited",
    linked:"Sarytogan Graphite Limited (ASX: SGA) through its 100% Kazakh subsidiary Ushtogan LLP; EBRD holds a 17.36% equity stake (acquired August 2024)",
    notes:"EBRD holds a 17.36% equity stake (acquired August 2024). Designated as EU Strategic Project under the Critical Raw Materials Act (June 2025).",
    desc:"Open-pit microcrystalline graphite mine in the Karaganda region of Central Kazakhstan. One of the world's largest and highest-grade graphite deposits (229 Mt at 28.9% TGC). Ultra-pure microcrystalline graphite through thermal purification.",
    applications:"Lithium-ion battery anodes (active anode material for EVs); industrial applications including lubricants, refractories, and nuclear moderators",
    eia:"Completed — environmental permit granted by the Ministry of Ecology and Natural Resources of Kazakhstan in December 2024. Three public review hearings completed with strong local support.",
    lic:"Granted — 25-year mining licence granted by Kazakhstan Ministry of Industry and Construction in January 2025 (covering 8.88 km2). Water licence also secured (February 2026). DFS scheduled mid-2026; construction planned 2027.",
    prod:"50,000 t/yr graphite concentrate (staged development strategy, per the 2024 PFS)",
    conflictDetail:"Community conflict status unknown. Three public environmental review hearings in nearby villages showed strong community support for the project. No documented opposition.",
    conflictLink:"",
    web:"https://www.sarytogangraphite.com.au/"
  },
  {
    id:11, name:"Songwe Hill Rare Earths",
    status:"active", type:"Extraction", country:"Malawi",
    lat:-15.6331472, lng:35.7933583,
    mat:"Rare Earth Elements for Magnets", neon:"#ff1744", fill:"#b30000",
    conflict:false,
    promoter:"Mkango Resources Ltd.",
    linked:"Mkango Resources Ltd. (AIM/TSX-V: MKA); through subsidiary Lancaster Exploration Ltd. In July 2025 Mkango signed a Business Combination Agreement with Crown PropTech Acquisitions (CPTK) to list Songwe Hill and its planned Pulawy (Poland) separation plant on NASDAQ as Mkango Rare Earths Limited. Both Songwe and Pulawy are designated EU Strategic Projects under the Critical Raw Materials Act.",
    notes:"Mkango Resources is a dual-listed (AIM London / TSX Venture) Canadian mineral exploration and development company focused on rare earths. A draft Form F-4 was confidentially filed with the SEC in February 2026.",
    desc:"Carbonatite-hosted rare earth element (REE) deposit on the north-facing slopes of Songwe Hill (990 m elevation). The mine would produce a purified mixed rare earth carbonate (MREC) grading 55% TREO, enriched in heavy and magnet rare earths (NdPr, Dy, Tb).",
    applications:"Permanent magnets for EV motors, wind turbines, and consumer electronics; other rare earth industrial uses",
    eia:"Completed — ESHIA approved by Malawi Environmental Protection Agency (MEPA) in January 2023. Undertaken by Digby Wells Environmental Limited in compliance with IFC Performance Standards and the Malawi Environmental Management Act.",
    lic:"Pending — Malawi Ministry of Justice appointed a London-based international law firm to carry out a final review of the Mining Development Agreement (MDA). Mining licence and MDA approval still pending. The project holds Retention Licence RTL 0001/21.",
    prod:"Expected ~5,954 t/yr in mixed rare earth carbonate during first five years of full production",
    conflictDetail:"Community conflict status unknown. No formal documented conflict. Community consultation was conducted as part of the ESHIA process.",
    conflictLink:"https://www.business-humanrights.org/my/from-us/briefings/strategic-projects-for-whom-challenges-and-local-realities-of-the-european-unions-strategic-mineral-projects/",
    web:"https://mkango.ca/projects/songwe/"
  },
  {
    id:12, name:"Tungsten West",
    status:"active", type:"Extraction", country:"United Kingdom",
    lat:50.4187917, lng:-4.0273389,
    mat:"Tungsten", neon:"#ffab00", fill:"#997a00",
    conflict:false,
    promoter:"Tungsten West PLC",
    linked:"Tungsten West PLC (LON: TUN); AMC Consultants (feasibility study); Lycopodium (process design); Duo Group PLC (crushing/screening/ore sorter facility construction); Gekko Systems (pressure jigs)",
    notes:"The company is seeking multi-million restart financing from UK, US, and EU government-backed agencies plus specialist mining funders and offtakers.",
    desc:"Restart of the Hemerdon Tungsten and Tin open-pit mine (former Hemerdon Ball/Drakelands Mine), located 11 km northeast of Plymouth in England. Previously operated from 2015-2018 under Wolf Minerals. Tungsten West completed its first trial tungsten concentrate production in November 2025. Restart of full-scale mining anticipated by late 2026, subject to financing close.",
    applications:"Tungsten for cutting tools, armour-piercing defence penetrators, wear-resistant alloys, electronics; tin as co-product; also produces aggregate as by-product",
    eia:"Completed — existing planning consent and environmental permits in place from the previous operating period. Environment Agency permit (JB3209MD) reissued September 2022.",
    lic:"Granted — base mining consent and Environment Agency permit in place. Feasibility Study updated in 2025. Restart financing of US$93 million being sought. Full restart of mining anticipated late 2026.",
    prod:"Expected yearly: 331,000 MTU of tungsten (WO3) and around 462 tonnes of tin",
    conflictDetail:"Community conflict status unknown. Local community concerns relate primarily to HGV traffic on haulage routes through Plympton. A pre-planning application and EIA scoping for secondary aggregate export was submitted to Devon County Council.",
    conflictLink:"",
    web:"https://www.tungstenwest.com/"
  },
  {
    id:13, name:"Zandkopsdrift",
    status:"active", type:"Extraction", country:"South Africa",
    lat:-30.862125, lng:17.9635972,
    mat:"Rare Earth Elements for Magnets, Manganese", neon:"#ff1744", fill:"#b30000",
    conflict:false,
    promoter:"Frontier Rare Earths Limited",
    linked:"Frontier Rare Earths Limited (private, Luxembourg-registered, EU-owned); Industrial Development Corporation (IDC, South African government-owned, invested US$20 million in equity in February 2026); Korea Mine Corporation / KOMIR (South Korean government, ~10% direct interest, acquired for US$24 million); Carester SAS (France, rare earth separation technology partner with offtake agreement signed February 2026)",
    notes:"Frontier Rare Earths is a private EU-owned company headquartered in Luxembourg. Designated as EU Strategic Project under CRMA (June 2025).",
    desc:"Open-pit rare earth and battery-grade manganese project in the Northern Cape Province of South Africa (Namaqualand / Kamiesberg area). The Zandkopsdrift carbonatite complex is approximately 1 km in diameter. The project will co-produce magnet rare earths (NdPr, Dy, Tb) and battery-grade manganese sulphate. Battery-grade manganese by-product revenue is expected to cover ~90% of rare earth production costs.",
    applications:"Permanent magnets for EV motors and wind turbines; battery-grade manganese sulphate for EV batteries (NMC cathodes)",
    eia:"Completed — project is fully permitted with mining right, environmental authorisation, social and labour plan and all other required permits for mine and process plant development in place.",
    lic:"Granted — mining right, environmental authorisation, and social and labour permits all granted. DFS commenced Q1 2025 and is fully funded; expected completion H1 2027. First production targeted 2030.",
    prod:"Mine life >45 years. Expected average: 17,000 t total rare earth oxides/yr + 4,000 t magnet rare earths/yr + >100,000 t battery grade manganese sulphate/yr",
    conflictDetail:"Community conflict status unknown. Local Zandkopsdrift communities are listed as project stakeholders. The project is in a remote part of Namaqualand, Northern Cape. No formal conflict documented publicly.",
    conflictLink:"",
    web:"https://frontierrareearths.com/"
  }
];

var SL = {active:"Active", halted:"Halted", cancelled:"Cancelled", pending:"Pending"};
